name: Create PDF
on: push

jobs:
  lint:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          node -v
          npm install
          npx md-to-pdf ./README.md
      - uses: actions/upload-artifact@v2
        with:
          name: create-pdf
          path: ./README.pdf